version: "3.3"

services:
  web:
    image: docker.pkg.github.com/khonkaen-hospital/donate-frontend/donate:latest
    ports:
      - 7006:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - brokernet
  api:
    image: docker.pkg.github.com/khonkaen-hospital/donate-backend/donate-api:latest
    expose:
      - 3000
    volumes:
      - ./.env:/app/.env
    networks:
      - brokernet
networks:
  brokernet:
    driver: bridge
